[project]
name = "file-manager-gui"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dearpygui>=2.1.0",
    "pillow>=11.3.0",
    "rich>=14.1.0",
]
